import { generateMessageIDV2 } from '@whiskeysockets/baileys';

export const CLIENT_MESSAGE_ID_PATTERN = /^3EB0[0-9A-F]{18}$/;

/**
 * Accept only the WhatsApp-compatible ID shape generated by the Inbox client.
 * Invalid or missing values are replaced server-side, so request data can never
 * inject arbitrary database identifiers into OutgoingMessage.
 */
export function createTrackedMessageId(requestedId?: unknown, userJid?: string): string {
    const normalizedId = typeof requestedId === 'string'
        ? requestedId.trim().toUpperCase()
        : '';

    return CLIENT_MESSAGE_ID_PATTERN.test(normalizedId)
        ? normalizedId
        : generateMessageIDV2(userJid);
}

